cifar10:
  class: CIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio

semi_supervised_cifar10:
  class: CIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
  num_labeled: 4000  # Number of labeled samples
