cifar10_train:
  class: CIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train: true  # Train or test
    download: true  # Download dataset if not present

cifar10_test:
  class: CIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train: false  # Train or test
    download: true  # Download dataset if not present
