cifar10:
  class: CIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio

semi_supervised_cifar10:
  class: SemiSupervisedCIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 4000  # Number of labeled samples

cityscapes_segmentation:
  class: CityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    mode: fine  # Dataset mode
    train_val_split: 2475 # Train/val split absolute number
