cifar10:
  class: CIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio

supervised_cifar10_4000l:
  class: SemiSupervisedCIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 4000  # Number of labeled samples
    force_transform: True  # Force transform

supervised_cifar10_2000l:
  class: SemiSupervisedCIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 2000  # Number of labeled samples
    force_transform: True  # Force transform

supervised_cifar10_1000l:
  class: SemiSupervisedCIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 1000  # Number of labeled samples
    force_transform: True  # Force transform

semi_supervised_cifar10_4000l:
  class: SemiSupervisedCIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 4000  # Number of labeled samples

semi_supervised_cifar10_2000l:
  class: SemiSupervisedCIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 2000  # Number of labeled samples

semi_supervised_cifar10_1000l:
  class: SemiSupervisedCIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 1000  # Number of labeled samples

unsupervised_cifar10:
  class: UnsupervisedCIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio

linear_eval_cifar10:
  class: LinearEvalCIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio

fine_tuning_cifar10_4000l:
  class: FineTuningTrainCIFAR10
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 4000  # Number of labeled samples

fine_tuning_cifar10_2000l:
  class: FineTuningTrainCIFAR10
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 2000  # Number of labeled samples

fine_tuning_cifar10_1000l:
  class: FineTuningTrainCIFAR10
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 1000  # Number of labeled samples

svhn:
  class: SVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio

supervised_svhn_1000l:
  class: SemiSupervisedSVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 1000  # Number of labeled samples
    force_transform: True  # Force transform

supervised_svhn_500l:
  class: SemiSupervisedSVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 500  # Number of labeled samples
    force_transform: True  # Force transform

supervised_svhn_250l:
  class: SemiSupervisedSVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 250  # Number of labeled samples
    force_transform: True  # Force transform

semi_supervised_svhn_1000l:
  class: SemiSupervisedSVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 1000  # Number of labeled samples

semi_supervised_svhn_500l:
  class: SemiSupervisedSVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 500  # Number of labeled samples

semi_supervised_svhn_250l:
  class: SemiSupervisedSVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 250  # Number of labeled samples

unsupervised_svhn:
  class: UnsupervisedSVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio

linear_eval_svhn:
  class: LinearEvalSVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio

fine_tuning_svhn_1000l:
  class: FineTuningTrainSVHN
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 1000  # Number of labeled samples

fine_tuning_svhn_500l:
  class: FineTuningTrainSVHN
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 500  # Number of labeled samples

fine_tuning_svhn_250l:
  class: FineTuningTrainSVHN
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 250  # Number of labeled samples

cityscapes_segmentation:
  class: CityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    mode: fine  # Dataset mode
    train_val_split: 2475 # Train/val split absolute number

semi_supervised_cityscapes_segmentation_77l:
  class: SemiSupervisedCityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 77  # Number of labeled samples

semi_supervised_cityscapes_segmentation_155l:
  class: SemiSupervisedCityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 155  # Number of labeled samples

semi_supervised_cityscapes_segmentation_309l:
  class: SemiSupervisedCityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 309  # Number of labeled samples

semi_supervised_cityscapes_segmentation_619l:
  class: SemiSupervisedCityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 619  # Number of labeled samples

semi_supervised_cityscapes_segmentation_1238l:
  class: SemiSupervisedCityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 1238  # Number of labeled samples

unsupervised_cityscapes:
  class: UnsupervisedCityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    mode: coarse  # Dataset mode
    train_val_split: 2475 # Train/val split absolute number

linear_eval_cityscapes:
  class: LinearEvalCityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    mode: fine  # Dataset mode
    train_val_split: 2475 # Train/val split absolute number

fine_tuning_cityscapes_segmentation_77l:
  class: FineTuningTrainCityscapesSeg
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    mode: fine  # Dataset mode
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 77  # Number of labeled samples

fine_tuning_cityscapes_segmentation_155l:
  class: FineTuningTrainCityscapesSeg
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    mode: fine  # Dataset mode
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 155  # Number of labeled samples

fine_tuning_cityscapes_segmentation_309l:
  class: FineTuningTrainCityscapesSeg
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    mode: fine  # Dataset mode
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 309  # Number of labeled samples

fine_tuning_cityscapes_segmentation_619l:
  class: FineTuningTrainCityscapesSeg
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    mode: fine  # Dataset mode
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 619  # Number of labeled samples

fine_tuning_cityscapes_segmentation_1238l:
  class: FineTuningTrainCityscapesSeg
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    mode: fine  # Dataset mode
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 1238  # Number of labeled samples
