cifar10:
  class: CIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio

semi_supervised_cifar10:
  class: SemiSupervisedCIFAR10  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 4000  # Number of labeled samples

svhn:
  class: SVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio

semi_supervised_svhn:
  class: SemiSupervisedSVHN  # Class name
  args:
    root: ./data/  # Path to dataset root
    train_val_split: 0.9  # Train/val split ratio
    num_labeled: 1000  # Number of labeled samples

cityscapes_segmentation:
  class: CityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    mode: fine  # Dataset mode
    train_val_split: 2475 # Train/val split absolute number

semi_supervised_cityscapes_segmentation_77l:
  class: SemiSupervisedCityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 77  # Number of labeled samples

semi_supervised_cityscapes_segmentation_155l:
  class: SemiSupervisedCityscapesSeg  # Class name
  args:
    root: /data/auto/cityscapes  # Path to dataset root
    train_val_split: 2475 # Train/val split absolute number
    num_labeled: 155  # Number of labeled samples
