cross_entropy:
  class: CrossEntropyLoss
  args: {}

cityscapes_cross_entropy:
  class: CrossEntropyLoss
  args: {}

cityscapes_dice:
  class: DiceLoss
  args:
    num_classes: 20
    average: "micro"
    ignore_index: 0
