cross_entropy:
  class: CrossEntropyLoss
  args: {}

cityscapes_cross_entropy:
  class: CrossEntropyLoss
  args:
    ignore_index: 255

cityscapes_dice:
  class: DiceLoss
  args:
    num_classes: 19
    average: "micro"
    ignore_index: 255
