cifar10_top1_accuracy:
  class: Accuracy
  args:
    task: "multiclass"
    num_classes: 10
    top_k: 1

cifar10_top5_accuracy:
  class: Accuracy
  args:
    task: "multiclass"
    num_classes: 10
    top_k: 5

cityscapes_jaccard:
  class: JaccardIndex
  args:
    task: "multiclass"
    num_classes: 30
    #ignore_index: 255
    validate_args: True #False

cityscapes_dice:
  class: Dice
  args:
    num_classes: 30
    average: "micro"
    #ignore_index: 255
