cifar10_top1_accuracy:
  class: Accuracy
  args:
    task: "multiclass"
    num_classes: 10
    top_k: 1

cifar10_top5_accuracy:
  class: Accuracy
  args:
    task: "multiclass"
    num_classes: 10
    top_k: 5

cityscapes_jaccard_macro:
  class: JaccardIndex
  args:
    task: "multiclass"
    average: "macro"
    num_classes: 20
    ignore_index: 0
    validate_args: False

cityscapes_jaccard_micro:
  class: JaccardIndex
  args:
    task: "multiclass"
    average: "micro"
    num_classes: 20
    ignore_index: 0
    validate_args: False

cityscapes_dice:
  class: Dice
  args:
    num_classes: 20
    average: "micro"
    ignore_index: 0
