cifar10_top1_accuracy:
  class: Accuracy
  args:
    task: "multiclass"
    num_classes: 10
    top_k: 1

cifar10_top5_accuracy:
  class: Accuracy
  args:
    task: "multiclass"
    num_classes: 10
    top_k: 5
