cifar10_wideresnet28_2:
  class: WideResNet
  args:
    num_classes: 10
    depth: 28
    widen_factor: 2

cityscapes_deeplabv3plus_resnet101:
  class: DeepLabV3PlusResNet101
  args:
    num_classes: 20
