cifar10_wideresnet28_2:
  class: WideResNet
  args:
    num_classes: 10
    depth: 28
    widen_factor: 2

cityscapes_deeplabv3_resnet101:
  class: DeepLabV3
  args:
    backbone: resnet101
    num_classes: 20
