cifar10_wideresnet28_2:
  class: WideResNet
  args:
    num_classes: 10
    depth: 28
    width: 2

cifar10_resnet50:
  class: ResNet50
  args:
    num_classes: 10

cifar10_resnet50_pretrained:
  class: ResNet50
  args:
    num_classes: 10
    pretrained: True

svhn_wideresnet28_2:
  class: WideResNet
  args:
    num_classes: 10
    depth: 28
    width: 2

svhn_resnet50:
  class: ResNet50
  args:
    num_classes: 10

svhn_resnet50_pretrained:
  class: ResNet50
  args:
    num_classes: 10
    pretrained: True

cityscapes_deeplabv3_resnet101:
  class: DeepLabV3
  args:
    backbone: resnet101
    num_classes: 20

cityscapes_deeplabv3_resnet101_pretrained:
  class: DeepLabV3
  args:
    backbone: resnet101
    num_classes: 20
    weights_backbone: DEFAULT

kitti_deeplabv3_resnet101:
  class: DeepLabV3
  args:
    backbone: resnet101
    num_classes: 20

kitti_deeplabv3_resnet101_pretrained:
  class: DeepLabV3
  args:
    backbone: resnet101
    num_classes: 20
    weights_backbone: DEFAULT
