supervised_wideresnet_sgd:
  class: SGD
  args:
    lr: 0.1  # Learning rate
    momentum: 0.9  # Momentum
    nesterov: True  # Nesterov momentum
    weight_decay: 0.0005  # Weight decay
    dampening: 0.0  # Dampening for momentum

cityscapes_sgd:
  class: SGD
  args:
    lr: 0.007  # Learning rate
    momentum: 0.9  # Momentum
    weight_decay: 0.0005  # Weight decay

pi_model_adam:
  class: Adam
  args:
    lr: 0.003  # Learning rate
    betas: [0.9, 0.999]  # Betas

temporal_adam:
  class: Adam
  args:
    lr: 0.003  # Learning rate
    betas: [0.9, 0.999]  # Betas

pi_model_seg_sgd:
  class: SGD
  args:
    lr: 0.007  # Learning rate
    momentum: 0.9  # Momentum
    weight_decay: 0.0005  # Weight decay
