## Supervised Learning
#### Classification
supervised_wideresnet_sgd:
  class: SGD
  args:
    lr: 0.1  # Learning rate
    momentum: 0.9  # Momentum
    nesterov: True  # Nesterov momentum
    weight_decay: 0.0005  # Weight decay
    dampening: 0.0  # Dampening for momentum

supervised_resnet50_sgd:
  class: SGD
  args:
    lr: 0.1  # Learning rate
    momentum: 0.9  # Momentum
    weight_decay: 0.0005  # Weight decay

supervised_resnet50_cifar10_adam:
  class: Adam
  args:
    lr: 0.001  # Learning rate

supervised_wideresnet_svhn_sgd:
  class: SGD
  args:
    lr: 0.1  # Learning rate
    momentum: 0.9  # Momentum
    nesterov: True  # Nesterov momentum
    weight_decay: 0.0005  # Weight decay
    dampening: 0.0  # Dampening for momentum

supervised_resnet50_svhn_adam:
  class: Adam
  args:
    lr: 0.001  # Learning rate

#### Segmentation
cityscapes_sgd:
  class: SGD
  args:
    lr: 0.007  # Learning rate
    momentum: 0.9  # Momentum
    weight_decay: 0.0005  # Weight decay


## Semi-supervised Learning
#### Classification
pi_model_adam:
  class: Adam
  args:
    lr: 0.003  # Learning rate
    betas: [0.9, 0.999]  # Betas

temporal_adam_cifar10:
  class: Adam
  args:
    lr: 0.003  # Learning rate
    betas: [0.9, 0.999]  # Betas

temporal_adam_svhn:
  class: Adam
  args:
    lr: 0.001  # Learning rate
    betas: [0.9, 0.999]  # Betas

mixmatch_cifar10_adam:
  class: Adam
  args:
    lr: 0.002  # Learning rate

mixmatch_svhn_adam:
  class: Adam
  args:
    lr: 0.002  # Learning rate

remixmatch_cifar10_adam:
  class: Adam
  args:
    lr: 0.002  # Learning rate

remixmatch_svhn_adam:
  class: Adam
  args:
    lr: 0.002  # Learning rate

fixmatch_cifar10_sgd:
  class: SGD
  args:
    lr: 0.03  # Learning rate
    momentum: 0.9  # Momentum
    nesterov: True  # Nesterov momentum
    weight_decay: 0.0005  # Weight decay

fixmatch_svhn_sgd:
  class: SGD
  args:
    lr: 0.03  # Learning rate
    momentum: 0.9  # Momentum
    nesterov: True  # Nesterov momentum
    weight_decay: 0.0005  # Weight decay

#### Segmentation
pi_model_seg_sgd:
  class: SGD
  args:
    lr: 0.01  # Learning rate
    momentum: 0.9  # Momentum
    nesterov: True  # Nesterov momentum
    weight_decay: 0.0005  # Weight decay

pi_model_seg_adam:
  class: Adam
  args:
    lr: 0.003  # Learning rate
    betas: [0.9, 0.999]  # Betas

mixmatch_seg_sgd:
  class: SGD
  args:
    lr: 0.01  # Learning rate
    momentum: 0.9  # Momentum
    nesterov: True  # Nesterov momentum
    weight_decay: 0.0005  # Weight decay

remixmatch_seg_sgd:
  class: SGD
  args:
    lr: 0.01  # Learning rate
    momentum: 0.9  # Momentum
    nesterov: True  # Nesterov momentum
    weight_decay: 0.0005  # Weight decay

remixmatch_seg_adam:
  class: Adam
  args:
    lr: 0.01  # Learning rate

fixmatch_seg_sgd:
  class: SGD
  args:
    lr: 0.01  # Learning rate
    momentum: 0.9  # Momentum
    nesterov: True  # Nesterov momentum
    weight_decay: 0.0005  # Weight decay

## Self-supervised Learning
#### Classification
simclr_cifar10_sgd:
  class: SGD
  args:
    lr: 0.3  # Learning rate
    momentum: 0.9  # Momentum
    nesterov: True  # Nesterov momentum
    weight_decay: 0.000001  # Weight decay

simclr_cifar10_adam:
  class: Adam
  args:
    lr: 0.0003  # Learning rate

simclr_svhn_adam:
  class: Adam
  args:
    lr: 0.0003  # Learning rate

byol_cifar10_adam:
  class: Adam
  args:
    lr: 0.0003  # Learning rate

byol_cifar10_lars:
  class: LARS
  args:
    lr: 0.3  # Learning rate
    momentum: 0.9  # Momentum
    weight_decay: 0.000001  # Weight decay

byol_svhn_adam:
  class: Adam
  args:
    lr: 0.0003  # Learning rate

moco_cifar10_adam:
  class: Adam
  args:
    lr: 0.0003  # Learning rate

moco_svhn_adam:
  class: Adam
  args:
    lr: 0.0003  # Learning rate

#### Segmentation
simclr_cityscapes_adam:
  class: Adam
  args:
    lr: 0.0003  # Learning rate

byol_cityscapes_adam:
  class: Adam
  args:
    lr: 0.0003  # Learning rate

moco_cityscapes_adam:
  class: Adam
  args:
    lr: 0.0003  # Learning rate
