## Supervised Learning
#### Classification
supervised_wideresnet_cifar_lr:
  class: MultiStepLR
  args:
    milestones: [60, 120, 160]
    gamma: 0.2

supervised_resnet50_cifar_lr:
  class: CosineAnnealingLR
  args:
    T_max: 100

supervised_wideresnet_svhn_lr:
  class: MultiStepLR
  args:
    milestones: [80, 120]
    gamma: 0.2

supervised_cifar10_cosine_lr:
  class: CosineAnnealingLR
  args:
    T_max: 200

#### Segmentation
cityscapes_polynomial_lr:
  class: PolynomialLR
  args:
    total_iters: 120
    power: 0.9

## Semi-supervised Learning
#### Classification
pi_model_exp_warmup_lr:
  class: ExpWarmupLR
  args:
    rampup_length: 80
    rampdown_length: 50
    num_epochs: 1000

temporal_exp_warmup_lr:
  class: ExpWarmupLR
  args:
    rampup_length: 80
    rampdown_length: 50
    num_epochs: 1000

mixmatch_cosine_lr:
  class: CosineAnnealingLR
  args:
    T_max: 1000

fixmatch_cosine_lr:
  class: CosineAnnealingLR
  args:
    T_max: 1000

#### Segmentation
pi_model_seg_polynomial_lr:
  class: PolynomialLR
  args:
    total_iters: 120
    power: 0.9

pi_model_seg_exp_warmup_lr:
  class: ExpWarmupLR
  args:
    rampup_length: 40
    rampdown_length: 30
    num_epochs: 120

pi_model_seg_cosine_lr:
  class: CosineAnnealingLR
  args:
    T_max: 120

mixmatch_seg_polynomial_lr:
  class: Polynomial
  args:
    total_iters: 120
    power: 0.9

mixmatch_seg_cosine_lr:
  class: CosineAnnealingLR
  args:
    T_max: 120

remixmatch_seg_cosine_lr:
  class: CosineAnnealingLR
  args:
    T_max: 120

fixmatch_seg_polynomial_lr:
  class: Polynomial
  args:
    total_iters: 120
    power: 0.9

fixmatch_seg_cosine_lr:
  class: CosineAnnealingLR
  args:
    T_max: 120

## Self-supervised Learning
#### Classification
simclr_cosine_lr:
  class: CosineAnnealingLR
  args:
    T_max: 100
    eta_min: 0.001
