supervised_wideresnet_cifar_lr:
  class: MultiStepLR
  args:
    milestones: [60, 120, 160]
    gamma: 0.2

supervised_wideresnet_svhn_lr:
  class: MultiStepLR
  args:
    milestones: [80, 120]
    gamma: 0.1

cityscapes_polynomial_lr:
  class: PolynomialLR
  args:
    total_iters: 120
    power: 0.9

pi_model_exp_warmup_lr:
  class: ExpWarmupLR
  args:
    rampup_length: 80
    rampdown_length: 50
    num_epochs: 1000

temporal_exp_warmup_lr:
  class: ExpWarmupLR
  args:
    rampup_length: 80
    rampdown_length: 50
    num_epochs: 1000

mixmatch_cosine_lr:
  class: CosineAnnealingLR
  args:
    T_max: 1000

fixmatch_cosine_lr:
  class: CosineAnnealingLR
  args:
    T_max: 1000

pi_model_seg_polynomial_lr:
  class: PolynomialLR
  args:
    total_iters: 120
    power: 0.9

pi_model_seg_exp_warmup_lr:
  class: ExpWarmupLR
  args:
    rampup_length: 32
    rampdown_length: 20
    num_epochs: 120

mixmatch_seg_polynomial_lr:
  class: Polynomial
  args:
    total_iters: 120
    power: 0.9
