supervised_wideresnet_cifar_lr:
  class: MultiStepLR
  args:
    milestones: [60, 120, 160]
    gamma: 0.2

pi_model_exp_warmup_lr:
  class: ExpWarmupLR
  args:
    rampup_length: 80
    rampdown_length: 50
    num_epochs: 300

temporal_exp_warmup_lr:
  class: ExpWarmupLR
  args:
    rampup_length: 80
    rampdown_length: 50
    num_epochs: 300

cityscapes_polinomial_lr:
  class: PolynomialLR
  args:
    total_iters: 200
    power: 0.9
