## Classification
simclr_cifar10:
  class: SimCLRCIFAR10
  args:
    temperature: 0.5
    projection_dim: 128
    color_jitter_strength: 1.0

simclr_svhn:
  class: SimCLRSVHN
  args:
    temperature: 0.5
    projection_dim: 128
    color_jitter_strength: 1.0

byol_cifar10:
  class: BYOLCIFAR10
  args:
    ema_decay: 0.99
    representation_size: 128
    prediction_size: 128
    projection_size: 128
    hidden_size: 2048
    image_size: 224
    color_jitter_strength: 1

byol_svhn:
  class: BYOLSVHN
  args:
    ema_decay: 0.99
    representation_size: 128
    prediction_size: 128
    projection_size: 128
    hidden_size: 2048
    image_size: 224
    color_jitter_strength: 1

moco_cifar10:
  class: MoCoCIFAR10
  args:
    queue_size: 65536
    ema_decay: 0.999
    temperature: 0.07
    representation_size: 128  # wideresnet=128; resnet50=2048
    projection_size: 128
    hidden_size: 512
    image_size: 224
    color_jitter_strength: 0.5

moco_svhn:
  class: MoCoSVHN
  args:
    queue_size: 65536
    ema_decay: 0.999
    temperature: 0.07
    representation_size: 128  # wideresnet=128; resnet50=2048
    projection_size: 128
    hidden_size: 512
    image_size: 224
    color_jitter_strength: 0.5

rotation_cifar10:
  class: RotationCIFAR10
  args:
    representation_size: 128  # wideresnet=128; resnet50=2048
    image_size: 224
    color_jitter_strength: 0.5

rotation_svhn:
  class: RotationSVHN
  args:
    representation_size: 128  # wideresnet=128; resnet50=2048
    image_size: 224
    color_jitter_strength: 0.5

## Segmentation
simclr_cityscapes:
  class: SimCLRCityscapes
  args:
    temperature: 0.5
    projection_dim: 128
    color_jitter_strength: 1.0

simclr_kitti:
  class: SimCLRKitti
  args:
    temperature: 0.5
    projection_dim: 128
    color_jitter_strength: 1.0

byol_cityscapes:
  class: BYOLCityscapes
  args:
    ema_decay: 0.99
    representation_size: 4096
    prediction_size: 128
    projection_size: 128
    hidden_size: 2048
    image_size: 512
    color_jitter_strength: 1

byol_kitti:
  class: BYOLKitti
  args:
    ema_decay: 0.99
    representation_size: 2048  # mobilenet=960; resnet101=2048
    prediction_size: 128
    projection_size: 128
    hidden_size: 2048
    image_size: [188, 621]
    color_jitter_strength: 1

moco_cityscapes:
  class: MoCoCityscapes
  args:
    queue_size: 65536
    ema_decay: 0.999
    temperature: 0.07
    representation_size: 2048
    projection_size: 128
    hidden_size: 512
    image_size: 512
    color_jitter_strength: 0.5

moco_kitti:
  class: MoCoKitti
  args:
    queue_size: 65536
    ema_decay: 0.999
    temperature: 0.07
    representation_size: 2048  # mobilenet=960; resnet101=2048
    projection_size: 128
    hidden_size: 512
    image_size: [188, 621]
    color_jitter_strength: 0.5

rotation_cityscapes:
  class: RotationCityscapes
  args:
    representation_size: 2048
    image_size: 512
    color_jitter_strength: 0.5
