simclr_cifar10:
  class: SimCLRCIFAR10
  args:
    temperature: 0.5
    projection_dim: 64
    color_jitter_strength: 1.0

simclr_svhn:
  class: SimCLRSVHN
  args:
    temperature: 0.5
    projection_dim: 64
    color_jitter_strength: 1.0
