## Classification
simclr_cifar10:
  class: SimCLRCIFAR10
  args:
    temperature: 0.5
    projection_dim: 128
    color_jitter_strength: 1.0

simclr_svhn:
  class: SimCLRSVHN
  args:
    temperature: 0.5
    projection_dim: 128
    color_jitter_strength: 1.0

byol_cifar10:
  class: BYOLCIFAR10
  args:
    ema_decay: 0.99
    representation_size: 2048
    prediction_size: 256
    projection_size: 256
    hidden_size: 4096
    image_size: 224
    color_jitter_strength: 1

## Segmentation
simclr_cityscapes:
  class: SimCLRCityscapes
  args:
    temperature: 0.5
    projection_dim: 128
    color_jitter_strength: 1.0
