pi_model:
  class: PiModel
  args:
    w_max: 100.0
    unsupervised_weight_rampup_length: 80

temporal_ensembling:
  class: TemporalEnsembling
  args:
    w_max: 30.0
    unsupervised_weight_rampup_length: 80
    accumlation_decay: 0.6
