pi_model_cifar10:
  class: PiModelCIFAR10
  args:
    w_max: 100.0
    unsupervised_weight_rampup_length: 240

pi_model_svhn:
  class: PiModelSVHN
  args:
    w_max: 100.0
    unsupervised_weight_rampup_length: 240

temporal_ensembling_cifar10:
  class: TemporalEnsemblingCIFAR10
  args:
    w_max: 30.0
    unsupervised_weight_rampup_length: 240
    accumlation_decay: 0.6

temporal_ensembling_svhn:
  class: TemporalEnsemblingSVHN
  args:
    w_max: 30.0
    unsupervised_weight_rampup_length: 480
    accumlation_decay: 0.6

mixmatch_cifar10:
  class: MixMatchCIFAR10
  args:
    alpha: 0.75
    w_max: 75.0
    unsupervised_weight_rampup_length: 240
    temperature: 0.5
    k: 2

mixmatch_svhn_1000l:
  class: MixMatchSVHN
  args:
    alpha: 0.75
    w_max: 250.0
    unsupervised_weight_rampup_length: 240
    temperature: 0.5
    k: 2

mixmatch_svhn_500l:
  class: MixMatchSVHN
  args:
    alpha: 0.75
    w_max: 250.0
    unsupervised_weight_rampup_length: 480
    temperature: 0.5
    k: 2

mixmatch_svhn_250l:
  class: MixMatchSVHN
  args:
    alpha: 0.75
    w_max: 250.0
    unsupervised_weight_rampup_length: 1000
    temperature: 0.5
    k: 2

remixmatch_cifar10:
  class: ReMixMatchCIFAR10
  args:
    alpha: 0.75
    wu_max: 1.5
    wu1_max: 0.5
    wr: 0.5
    unsupervised_weight_rampup_length: 240
    temperature: 0.5
    k: 8

remixmatch_svhn:
  class: ReMixMatchSVHN
  args:
    alpha: 0.75
    wu_max: 1.5
    wu1_max: 0.5
    wr: 0.5
    unsupervised_weight_rampup_length: 240
    temperature: 0.5
    k: 8

remixmatch_svhn_250l:
  class: ReMixMatchSVHN
  args:
    alpha: 0.75
    wu_max: 1.5
    wu1_max: 0.5
    wr: 0.5
    unsupervised_weight_rampup_length: 500
    temperature: 0.5
    k: 8

fixmatch_cifar10:
  class: FixMatchCIFAR10
  args:
    wu: 1
    confidence: 0.95

fixmatch_svhn:
  class: FixMatchSVHN
  args:
    wu: 1
    confidence: 0.95

pi_model_cityscapes_seg:
  class: PiModelCityscapesSeg
  args:
    w_max: 1.0
    unsupervised_weight_rampup_length: 60

mixmatch_cityscapes_seg:
  class: MixMatchCityscapesSeg
  args:
    alpha: 0.75
    w_max: 0.50
    unsupervised_weight_rampup_length: 60
    temperature: 0.5
    k: 2

remixmatch_cityscapes_seg:
  class: ReMixMatchCityscapesSeg
  args:
    alpha: 0.75
    wu_max: 0.75
    wu1_max: 0.25
    wr: 0.5
    unsupervised_weight_rampup_length: 40
    temperature: 0.5
    k: 2

fixmatch_cityscapes_seg:
  class: FixMatchCityscapesSeg
  args:
    wu: 1
    confidence: 0.50
