pi_model_cifar10:
  class: PiModelCIFAR10
  args:
    w_max: 100.0
    unsupervised_weight_rampup_length: 80

pi_model_svhn:
  class: PiModelSVHN
  args:
    w_max: 100.0
    unsupervised_weight_rampup_length: 80

temporal_ensembling_cifar10:
  class: TemporalEnsemblingCIFAR10
  args:
    w_max: 30.0
    unsupervised_weight_rampup_length: 80
    accumlation_decay: 0.6

temporal_ensembling_svhn:
  class: TemporalEnsemblingSVHN
  args:
    w_max: 30.0
    unsupervised_weight_rampup_length: 80
    accumlation_decay: 0.6

mixmatch_cifar10:
  class: MixMatchCIFAR10
  args:
    alpha: 0.75
    w_max: 75.0
    unsupervised_weight_rampup_length: 120
    temperature: 0.5
    k: 2

mixmatch_svhn:
  class: MixMatchSVHN
  args:
    alpha: 0.75
    w_max: 75.0
    unsupervised_weight_rampup_length: 80
    temperature: 0.5
    k: 2

pi_model_cityscapes_seg:
  class: PiModelCityscapesSeg
  args:
    w_max: 50.0
    unsupervised_weight_rampup_length: 80

mixmatch_cityscapes_seg:
  class: MixMatchCityscapesSeg
  args:
    alpha: 0.75
    w_max: 75.0
    unsupervised_weight_rampup_length: 80
    temperature: 0.5
    k: 2
