pi_model_cifar10:
  class: PiModelCIFAR10
  args:
    w_max: 100.0
    unsupervised_weight_rampup_length: 80

pi_model_svhn:
  class: PiModelSVHN
  args:
    w_max: 100.0
    unsupervised_weight_rampup_length: 80

temporal_ensembling_cifar10:
  class: TemporalEnsemblingCIFAR10
  args:
    w_max: 30.0
    unsupervised_weight_rampup_length: 80
    accumlation_decay: 0.6

temporal_ensembling_svhn:
  class: TemporalEnsemblingSVHN
  args:
    w_max: 30.0
    unsupervised_weight_rampup_length: 80
    accumlation_decay: 0.6

pi_model_cityscapes_seg:
  class: PiModelCityscapesSeg
  args:
    w_max: 10.0
    unsupervised_weight_rampup_length: 80
